---
# Variables that are less likely to change between environments
jenkins_repo_deb: "deb https://pkg.jenkins.io/debian-stable binary/"
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
