---
# Variables that are less likely to change between environments
jenkins_controller_repo_deb: "deb https://pkg.jenkins.io/debian-stable binary/"
jenkins_controller_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

# Backwards compatibility
jenkins_repo_deb: "{{ jenkins_controller_repo_deb }}"
jenkins_repo_key_url: "{{ jenkins_controller_repo_key_url }}"
