---
galaxy_info:
  author: venkat
  description: Role to install and configure Jenkins controller
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye

dependencies: []
